# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        minProfilePicture:
            quality: 85
            filters:
                thumbnail:
                    size: [ 300, 290 ]
                    # crop the input image, if required
                    mode: outbound

        actuPicture:
            quality: 85
            filters:
                thumbnail:
                    size: [ 470, 295 ]
                    mode: outbound
